onflow/FRW-monorepo

packages/stores/src/storageStore.query.ts

fix: incompatible check

---

packages/screens/src/send/SendToScreen.query.tsx

fix: scan qr code

---

CLAUDE.md
apps/extension/src/bridge/PlatformContext.tsx
apps/extension/src/bridge/PlatformImpl.ts
apps/react-native/src/App.tsx
apps/react-native/src/bridge/PlatformImpl.ts
packages/context/src/interfaces/PlatformSpec.ts
packages/screens/src/index.ts
packages/screens/src/lib/i18n.ts

Release fix 18n

---

.github/pull_request_template.md
.github/workflows/check-linked-issues.yml

chore: Update pull_request_template.md

---

apps/extension/src/core/service/userWallet.ts

fix: use address to generate index for emoji

---

.gitmodules

ci: update iOS default branch to dev

---

apps/react-native/src/bridge/NativeFRWBridge.ts
apps/react-native/src/bridge/PlatformImpl.ts

feat: add toast bridge

---

packages/api/js_swagger.json
packages/api/src/codegen/goService.generated.ts
packages/api/src/codegen/service.generated.ts

feat: add payer api for codegen

---

packages/api/js_swagger.json
packages/api/src/codegen/service.generated.ts

chore: fix type error of swagger

---

apps/extension/src/core/service/userWallet.ts

fix: update user evm to use random avatar

---

.github/workflows/android.yml

ci: update android ci

---

.github/workflows/android.yml
docs/Android-CI-CD.md

249 fix android ci build

---

apps/extension/src/bridge/PlatformImpl.ts
apps/react-native/src/bridge/NativeFRWBridge.ts
apps/react-native/src/bridge/PlatformImpl.ts
packages/context/src/interfaces/PlatformSpec.ts
packages/screens/src/send/SelectTokensScreen.query.tsx

feat: add watch address #335

---

apps/extension/src/content-script/pageProvider/eth/index.ts

fix: window inject function name

---

packages/ui/src/components/ERC1155QuantitySelector.tsx

fix: selector icon color

---

.claude/settings.local.json
.github/workflows/balance-monitor.yml
scripts/monitor-balance.js

ci: add payer address monitor

---

packages/screens/src/send/NFTListScreen.query.tsx
packages/ui/src/components/NFTGrid.tsx

fix: watch nft list and react native scroll

---

docs/epics/eoa-support.md

docs: add EPIC doc for EOA support

---

packages/api/js_swagger.json
packages/api/src/codegen/service.generated.ts

feat: add max fee for payer status

---

packages/screens/src/send/SendTokensScreen.query.tsx

Closes #440
https://github.com/user-attachments/assets/e80b5ab0-a033-4b99-8ca1-abb5c79cb690

fix: crash on rn due to func not exist

---

packages/screens/package.json
packages/screens/src/send/SendTokensScreen.query.tsx
packages/screens/tsup.config.ts

Closes #440
https://github.com/user-attachments/assets/770383e7-6378-41fe-813f-f103003149e6

chore: clean up the keyboard code

---

apps/extension/src/ui/views/TokenDetail/TokenInfoCard.tsx

fix: selectoken format from token detail page

---

packages/ui/src/theme.ts

fix: button color

---

packages/ui/src/components/AddressBookSection.tsx
packages/ui/src/theme.ts

Merge dev content to release

---

packages/screens/src/send/SendToScreen.query.tsx
packages/ui/src/components/AddressBookSection.tsx
packages/ui/src/components/ProfileList.tsx
packages/ui/src/components/RecipientList.tsx
packages/ui/src/components/SearchableTabLayout.tsx
packages/ui/src/foundation/Skeleton.tsx
packages/ui/src/types/index.ts
packages/ui/stories/Skeleton.stories.tsx

Closes #460
https://github.com/user-attachments/assets/012130f7-25e7-4b71-a15f-31e56687b54c

feat: update skeleton view with pulse animation

---

apps/react-native/src/navigation/AppNavigator.tsx
packages/screens/src/send/SendTokensScreen.query.tsx

fix: balance display 0 issue

---

packages/ui/src/foundation/Button.tsx
packages/ui/stories/Button.stories.tsx

Closes #476
https://github.com/user-attachments/assets/9c9f4aea-2339-4d97-b7bc-a08c88eccb2a

fix: don't use default bg for hover button inverse

---

.github/workflows/extension-build.yml
apps/extension/_raw/manifest/manifest.pro.json
apps/extension/src/ui/index.html

fix: update permission

---

packages/screens/src/send/NFTDetailScreen.query.tsx
packages/screens/src/send/SendSummaryScreen.query.tsx
packages/stores/src/sendStore.ts
packages/ui/src/components/ConfirmationDrawer.tsx
packages/workflow/src/send/validation.ts

Closes #463, #388
https://github.com/user-attachments/assets/2cd00ebb-b597-4344-b5bf-27c88f0c4bd2
https://github.com/user-attachments/assets/af96aa8f-0def-4ede-ab18-86abdf2c8fd1
https://github.com/user-attachments/assets/a451d5ec-1a83-40b7-b6a8-71ac131c5778
Closes #463

fix: erc1155 send on android / edit icon NFTs navigation

---

apps/extension/_raw/manifest/manifest.pro.json

fix: remove unused permission

---

.github/workflows/release-notes.yml
packages/ui/src/components/AddressBookSection.tsx
scripts/release-notes/README.md
scripts/release-notes/collect_commits.sh
scripts/release-notes/generate_with_ai.sh
scripts/release-notes/sanitize_notes.sh
scripts/release-notes/update_release_body.sh

489 ci update release note generator

---

packages/ui/src/foundation/Skeleton.tsx
packages/ui/src/theme.ts

fix: theme color cleanup

---

.github/workflows/android.yml
.github/workflows/release-notes.yml
scripts/release-notes/sanitize_notes.sh
scripts/release-notes/update_release_body.sh

ci: update android ci with release tag trigger

---

.github/workflows/android.yml

ci: update android ci for attachment download

---

scripts/release-notes/sanitize_notes.sh

ci: update android ci settings

---

.github/workflows/release-notes.yml
scripts/release-notes/collect_commits.sh

ci: update release note script
